name: AI PR Review
'on':
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
permissions:
  contents: read
  pull-requests: write
jobs:
  ai-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests pyyaml
    - name: Run AI Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python cursor_pr_review_final.py review-pr owner/repo ${{ github.event.pull_request.number
        }}
