name: AI PR Review
'on':
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
permissions:
  contents: read
  pull-requests: write
jobs:
  coderabbit-review:
    name: CodeRabbit Review
    runs-on: ubuntu-latest
    steps:
    - name: CodeRabbit Review
      uses: coderabbitai/coderabbit-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  ai-review:
    name: Custom AI Code Review
    runs-on: ubuntu-latest
    needs:
    - coderabbit-review
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests pyyaml
    - name: Run AI Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python cursor_pr_review.py review-pr jxwalker/cursor-pr-review ${{ github.event.pull_request.number
        }}
